apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: petclinic-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /api/vet
      - /api/customer
      - /api/visit
---
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: ui-traefik-service
  namespace: default

spec:
  weighted:
    services:
      - name: api-gateway
        namespace: spring-petclinic
        port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: vets-traefik-service
  namespace: default

spec:
  weighted:
    services:
      - name: vets-service
        namespace: spring-petclinic
        port: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: visits-traefik-service
  namespace: default

spec:
  weighted:
    services:
      - name: visits-service
        namespace: spring-petclinic
        port: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: customers-traefik-service
  namespace: default

spec:
  weighted:
    services:
      - name: customers-service
        namespace: spring-petclinic
        port: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: petclinic
spec:
  entryPoints:
    - web
  routes:
    - match: HostRegexp(`{host:.+}`)
      kind: Rule
      services:
        - name: ui-traefik-service
          kind : TraefikService
    - match: PathPrefix(`/api/vet`)
      kind: Rule
      services:
        - name: vets-traefik-service
          kind: TraefikService
      middlewares:
        - name: petclinic-stripprefix
    - match: PathPrefix(`/api/customer`)
      kind: Rule
      services:
        - name: customers-traefik-service
          kind : TraefikService
      middlewares:
        - name: petclinic-stripprefix
    - match: PathPrefix(`/api/visit`)
      kind: Rule
      services:
        - name: visits-traefik-service
          kind : TraefikService
      middlewares:
        - name: petclinic-stripprefix
